### ISSUE TITLE
Error message in 1.7 causes adapter to crash

### ISSUE THREAD

**Issue by Claus1985** [ioBroker/ioBroker.wolf#103]
The following error accrued and caused the adapter to crash:

`
host.Schaltzentrale2 | 2023-04-18 08:23:20.704 | error | instance system.adapter.wolf.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
host.Schaltzentrale2 | 2023-04-18 08:23:20.704 | error | Caught by controller[1]: at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
host.Schaltzentrale2 | 2023-04-18 08:23:20.704 | error | Caught by controller[1]: at Socket.Readable.push (node:internal/streams/readable:234:10)
host.Schaltzentrale2 | 2023-04-18 08:23:20.704 | error | Caught by controller[1]: at readableAddChunk (node:internal/streams/readable:297:9)
host.Schaltzentrale2 | 2023-04-18 08:23:20.704 | error | Caught by controller[1]: at addChunk (node:internal/streams/readable:324:12)
host.Schaltzentrale2 | 2023-04-18 08:23:20.704 | error | Caught by controller[1]: at Socket.emit (node:domain:489:12)
host.Schaltzentrale2 | 2023-04-18 08:23:20.703 | error | Caught by controller[1]: at Socket.emit (node:events:513:28)
host.Schaltzentrale2 | 2023-04-18 08:23:20.703 | error | Caught by controller[1]: at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.wolf/main.js:896:27)
host.Schaltzentrale2 | 2023-04-18 08:23:20.703 | error | Caught by controller[1]: at Buffer.readUInt16BE (node:internal/buffer:334:5)
host.Schaltzentrale2 | 2023-04-18 08:23:20.703 | error | Caught by controller[1]: at boundsError (node:internal/buffer:88:9)
host.Schaltzentrale2 | 2023-04-18 08:23:20.703 | error | Caught by controller[1]: at new NodeError (node:internal/errors:399:5)
host.Schaltzentrale2 | 2023-04-18 08:23:20.703 | error | Caught by controller[1]: RangeError: The value of "offset" is out of range. It must be >= 0 and <= 6. Received 12
host.Schaltzentrale2 | 2023-04-18 08:23:20.701 | error | Caught by controller[0]: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason:
wolf.0 | 2023-04-18 08:23:20.038 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
wolf.0 | 2023-04-18 08:23:20.004 | error | Exception-Code: ERR_OUT_OF_RANGE: The value of "offset" is out of range. It must be >= 0 and <= 6. Received 12
wolf.0 | 2023-04-18 08:23:20.003 | error | RangeError: The value of "offset" is out of range. It must be >= 0 and <= 6. Received 12 at new NodeError (node:internal/errors:399:5) at boundsError (node:internal/buffer:88:9) at Buffer.readUInt16BE (node:internal/buffer:334:5) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.wolf/main.js:896:27) at Socket.emit (node:events:513:28) at Socket.emit (node:domain:489:12) at addChunk (node:internal/streams/readable:324:12) at readableAddChunk (node:internal/streams/readable:297:9) at Socket.Readable.push (node:internal/streams/readable:234:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
wolf.0 | 2023-04-18 08:23:19.993 | error | unhandled promise rejection: The value of "offset" is out of range. It must be >= 0 and <= 6. Received 12
wolf.0 | 2023-04-18 08:23:19.992 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
`

 - Adapter version: 1.7

**Comment by Claus1985** [comment]
ok my fault... router log says there was a reset in that time window.. that explains the error..
