### ISSUE TITLE
Error: Value out of range

### ISSUE THREAD

**Issue by Streit187** [ioBroker/ioBroker.wolf#107]
From time to time the following error comes up:

`host.raspberrypi | 2023-08-10 00:28:43.411 | error | instance system.adapter.wolf.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
wolf.0 | 2023-08-10 00:28:42.687 | error | Exception-Code: ERR_OUT_OF_RANGE: The value of "offset" is out of range. It must be >= 0 and <= 8. Received 12
wolf.0 | 2023-08-10 00:28:42.686 | error | RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 8. Received 12 at new NodeError (node:internal/errors:387:5) at boundsError (node:internal/buffer:86:9) at Buffer.readUInt16BE (node:internal/buffer:332:5) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.wolf/main.js:896:27) at Socket.emit (node:events:513:28) at addChunk (node:internal/streams/readable:315:12) at readableAddChunk (node:internal/streams/readable:289:9) at Socket.Readable.push (node:internal/streams/readable:228:10) at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
wolf.0 | 2023-08-10 00:28:42.682 | error | unhandled promise rejection: The value of "offset" is out of range. It must be >= 0 and <= 8. Received 12
wolf.0 | 2023-08-10 00:28:42.663 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by Streit187** [comment]
Yes, sure.

**Comment by Streit187** [comment]
`2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 12
2023-08-13 21:28:00.581  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.12.Status 3-Wege-Umschaltventil: false
2023-08-13 21:28:00.581  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f0860000000000
2023-08-13 21:28:00.585  - [31merror[39m: wolf.0 (1309) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2023-08-13 21:28:00.585  - [31merror[39m: wolf.0 (1309) unhandled promise rejection: The value of "offset" is out of range. It must be >= 0 and <= 9. Received 12
2023-08-13 21:28:00.587  - [31merror[39m: wolf.0 (1309) RangeError [ERR_OUT_OF_RANGE]: The value of "offset" is out of range. It must be >= 0 and <= 9. Received 12
    at new NodeError (node:internal/errors:387:5)
    at boundsError (node:internal/buffer:86:9)
    at Buffer.readUInt16BE (node:internal/buffer:332:5)
    at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.wolf/main.js:896:27)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)
2023-08-13 21:28:00.587  - [31merror[39m: wolf.0 (1309) Exception-Code: ERR_OUT_OF_RANGE: The value of "offset" is out of range. It must be >= 0 and <= 9. Received 12
2023-08-13 21:28:00.621  - [32minfo[39m: wolf.0 (1309) terminating
2023-08-13 21:28:00.622  - [33mwarn[39m: wolf.0 (1309) Terminated (UNCAUGHT_EXCEPTION): Without reason
2023-08-13 21:28:01.302  - [31merror[39m: host.raspberrypi instance system.adapter.wolf.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
2023-08-13 21:28:01.304  - [32minfo[39m: host.raspberrypi Restart adapter system.adapter.wolf.0 because enabled`

**Comment by Apollon77** [comment]
Generell perfekt, kannst DU bitte noch ein paar zeilen von davor hinzufügen für mehr Kontext beim ansehen?

**Comment by Streit187** [comment]
Sehr gerne:

2023-08-13 21:28:00.578  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 9
2023-08-13 21:28:00.578  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.9.Status Brenner / Flamme: false
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f086000a000000
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 10
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.10.Status Heizkreispumpe: false
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f086000b000000
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 11
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.11.Status Speicherladepumpe: false
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f086000c000000
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 12
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.12.Status 3-Wege-Umschaltventil: false
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f0860009000000
2023-08-13 21:28:00.579  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 9
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.9.Status Brenner / Flamme: false
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f086000a000000
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 10
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.10.Status Heizkreispumpe: false
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f086000b000000
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Data for hg1_t : 11
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Set Value for hg1_t.11.Status Speicherladepumpe: false
2023-08-13 21:28:00.580  - [34mdebug[39m: wolf.0 (1309) Acknowledge 0620f080001104000000f086000c000000

...und so geht es eine ganze Weile, sprich da kommen sämtliche Daten rein.

**Comment by fred0815** [comment]
Welche Software Versionen setzte du beim Adapter und beim ISM8i ein?
In Zeile "2023-08-13 21:28:00.579 - �[34mdebug�[39m: wolf.0 (1309) Data for hg1_t : 12" scheint es ja zu gehen....🤷‍♂️

**Comment by Streit187** [comment]
Hi @fred0815 
der Adapter ist 1.7.0 und ism8i hat ebenfalls die Version 1.70.
