### ISSUE TITLE
Lot of Datapoints missing. 

### ISSUE THREAD

**Issue by fastsonic** [ioBroker/ioBroker.wolf#113]
How can i see the Infos from this Datapoint, can i edit it by my selfe ?
Its a Wolf CHA10 Wärmepumpe

wolf.0 | 2023-10-27 15:26:07.065 | info | For datapoint 362 no device defined.
wolf.0 | 2023-10-27 15:26:06.417 | info | For datapoint 199 no device defined.
wolf.0 | 2023-10-27 15:26:04.737 | info | For datapoint 198 no device defined.
wolf.0 | 2023-10-27 15:26:04.577 | info | For datapoint 197 no device defined.
wolf.0 | 2023-10-27 15:25:32.364 | info | For datapoint 767 no device defined.
wolf.0 | 2023-10-27 15:25:27.791 | info | For datapoint 372 no device defined.
wolf.0 | 2023-10-27 15:25:26.537 | info | For datapoint 364 no device defined.
wolf.0 | 2023-10-27 15:25:18.314 | info | For datapoint 363 no device defined.

and some more..

wolf.0 | 2023-10-27 15:34:06.419 | info | For datapoint 106 no device defined.
wolf.0 | 2023-10-27 15:34:06.419 | debug | Data for km1_t : 106
wolf.0 | 2023-10-27 15:34:06.419 | debug | Acknowledge 0620f080001104000000f086006a000000
wolf.0 | 2023-10-27 15:34:06.419 | debug | Received Data from 10.0.1.21:52431: 0620f080001504000000f006006a0001006a030101
wolf.0 | 2023-10-27 15:34:06.409 | info | For datapoint 128 no device defined.
wolf.0 | 2023-10-27 15:34:06.409 | debug | Data for mm3_t : 128
wolf.0 | 2023-10-27 15:34:06.317 | info | For datapoint 106 no device defined.
wolf.0 | 2023-10-27 15:34:06.317 | debug | Data for km1_t : 106
wolf.0 | 2023-10-27 15:34:06.317 | debug | Acknowledge 0620f080001104000000f086006a000000
wolf.0 | 2023-10-27 15:34:06.317 | debug | Received Data from 10.0.1.21:52431: 0620f080001504000000f006006a0001006a030101
wolf.0 | 2023-10-27 15:34:06.315 | info | For datapoint 148 no device defined.
wolf.0 | 2023-10-27 15:34:06.315 | debug | Data for cwl_t : 148
wolf.0 | 2023-10-27 15:34:06.315 | debug | Acknowledge 0620f080001104000000f0860094000000
wolf.0 | 2023-10-27 15:34:06.315 | debug | Received Data from 10.0.1.21:52431: 0620f080001504000000f006009400010094030101

**Comment by fastsonic** [comment]
> How can i see the Infos from this Datapoint, can i edit it by my selfe ? 
Its a Wolf CHA10 Wärmepumpe


wolf.0 | 2023-10-27 15:26:07.065 | info | For datapoint 362 no device defined.
-- | -- | -- | --
wolf.0 | 2023-10-27 15:26:06.417 | info | For datapoint 199 no device defined.
wolf.0 | 2023-10-27 15:26:04.737 | info | For datapoint 198 no device defined.
wolf.0 | 2023-10-27 15:26:04.577 | info | For datapoint 197 no device defined.
wolf.0 | 2023-10-27 15:25:32.364 | info | For datapoint 767 no device defined.
wolf.0 | 2023-10-27 15:25:27.791 | info | For datapoint 372 no device defined.
wolf.0 | 2023-10-27 15:25:26.537 | info | For datapoint 364 no device defined.
wolf.0 | 2023-10-27 15:25:18.314 | info | For datapoint 363 no device defined.

**Comment by franks06347** [comment]
Hallo,
tritt bei mir auch auf.
Viele Grüße
Frank
[iobroker Wolf _LOG 2023-11-06.log](https://github.com/ioBroker/ioBroker.wolf/files/13266105/iobroker.Wolf._LOG.2023-11-06.log)

**Comment by fred0815** [comment]
pls download both files from issue #96, rename and copy them to iobroker and restart the adapter. should be fixed afterwards.
"datapoints,json" to "/opt/iobroker/node_modules/iobroker.wolf/js" 

and

"main.js" to "/opt/iobroker/node_modules/iobroker.wolf"

**Comment by fastsonic** [comment]
seems not working in my enviroment !?
wolf.0
2023-11-16 15:37:47.999	info	terminating

wolf.0
2023-11-16 15:37:47.977	error	undefined is not a valid state value

wolf.0
2023-11-16 15:37:47.976	error	Error: undefined is not a valid state value at Object.maybeCallbackWithError (/opt/iobroker/node_modules/@iobroker/js-controller-common/src/lib/common/maybeCallback.ts:136:17) at AdapterClass._setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7593:26) at AdapterClass.setState (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:7551:21) at setState (/opt/iobroker/node_modules/iobroker.wolf/main.js:899:17) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.wolf/main.js:949:31) at Socket.emit (node:events:517:28) at Socket.emit (node:domain:489:12) at addChunk (node:internal/streams/readable:335:12) at readableAddChunk (node:internal/streams/readable:308:9) at Socket.Readable.push (node:internal/streams/readable:245:10)

wolf.0
2023-11-16 15:37:47.862	error	unhandled promise rejection: undefined is not a valid state value

wolf.0
2023-11-16 15:37:47.862	error	Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

**Comment by fastsonic** [comment]
change back to old files:
Adapter is working wihst some messages..

wolf.0
2023-11-16 15:42:29.665	info	For datapoint 372 no device defined.

wolf.0
2023-11-16 15:42:29.481	info	For datapoint 364 no device defined.

wolf.0
2023-11-16 15:42:28.141	info	For datapoint 767 no device defined.

wolf.0
2023-11-16 15:42:17.169	info	For datapoint 363 no device defined.

wolf.0
2023-11-16 15:42:17.166	info	For datapoint 362 no device defined.

wolf.0
2023-11-16 15:42:15.137	info	For datapoint 199 no device defined.

wolf.0
2023-11-16 15:42:14.977	info	For datapoint 198 no device defined.

wolf.0
2023-11-16 15:42:14.839	info	For datapoint 197 no device defined.

**Comment by Zefau** [comment]
Is there a way to figure out what the missing datapoints are for and add them (incl. an appropriate description) ourselves to the adapter ?

----------------


wolf.0 | 2023-12-27 22:39:56.537 | warn | State value to set for "wolf.0.hg0_t.178" has value "-0.1" less than min "0"
-- | -- | -- | --
wolf.0 | 2023-12-27 22:23:53.740 | error | Can't parse DP : 345, type DPT_Unknown2 - data: 0620f080001404000000f0060159000101590300 - length: 20
wolf.0 | 2023-12-27 22:23:53.548 | error | Can't parse DP : 344, type DPT_Unknown2 - data: 0620f080001404000000f0060158000101580300 - length: 20
wolf.0 | 2023-12-27 22:23:50.343 | error | Can't parse DP : 179, type DPT_Power - data: 0620f080001404000000f00600b3000100b30300 - length: 20
wolf.0 | 2023-12-27 22:23:44.477 | info | State value to set for "wolf.0.cwl_t.149" has to be type "number" but received type "string"
wolf.0 | 2023-12-27 22:08:52.069 | warn | State value to set for "wolf.0.hg0_t.178" has value "-0.1" less than min "0"
wolf.0 | 2023-12-27 21:53:33.036 | warn | State value to set for "wolf.0.hg0_t.178" has value "-0.2" less than min "0"
wolf.0 | 2023-12-27 21:52:52.153 | error | Can't parse DP : 345, type DPT_Unknown2 - data: 0620f080001404000000f0060159000101590300 - length: 20
wolf.0 | 2023-12-27 21:52:52.041 | error | Can't parse DP : 344, type DPT_Unknown2 - data: 0620f080001404000000f0060158000101580300 - length: 20
wolf.0 | 2023-12-27 21:52:49.029 | error | Can't parse DP : 179, type DPT_Power - data: 0620f080001404000000f00600b3000100b30300 - length: 20
wolf.0 | 2023-12-27 21:52:44.860 | info | State value to set for "wolf.0.cwl_t.149" has to be type "number" but received type "string"
wolf.0 | 2023-12-27 21:36:53.791 | warn | State value to set for "wolf.0.hg0_t.178" has value "-0.2" less than min "0"
wolf.0 | 2023-12-27 21:26:07.356 | warn | State value to set for "wolf.0.hg0_t.178" has value "-0.1" less than min "0"
wolf.0 | 2023-12-27 21:21:30.145 | error | Can't parse DP : 345, type DPT_Unknown2 - data: 0620f080001404000000f0060159000101590300 - length: 20
wolf.0 | 2023-12-27 21:21:30.025 | error | Can't parse DP : 344, type DPT_Unknown2 - data: 0620f080001404000000f0060158000101580300 - length: 20
wolf.0 | 2023-12-27 21:21:26.267 | error | Can't parse DP : 179, type DPT_Power - data: 0620f080001404000000f00600b3000100b30300 - length: 20
wolf.0 | 2023-12-27 21:21:20.832 | info | State value to set for "wolf.0.cwl_t.149" has to be type "number" but received type "string"
wolf.0 | 2023-12-27 21:12:18.947 | warn | State value to set for "wolf.0.hg0_t.178" has value "-0.5" less than min "0"
wolf.0 | 2023-12-27 21:11:29.128 | warn | State value to set for "wolf.0.hg0_t.178" has value "-0.7" less than min "0"
